# Site settings
title: Kushagra Khare
description: Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g.

# User settings
username: Kushagra Khare
user_title: AR | VR | Game | Graphics Programmer
user_description: Welcome to my little slice of the interwebs. I'm Kushagra and as you've probably guessed from the title of this website I'm a huge game programming, augmented & virtual reality and graphics enthusiast. In my spare time, I am messing around with game engines, figuring out new and interesting ways of doing things, working on lighting reconstruction for AR or even playing games like FIFA and Mario. I enjoy working with people that share similar interests so feel free to get in touch with me.
user_description_2: Below you'll find some of my projects I've been working on lately. You can find out the details and repository and of several of my projects on Github.
twitter_username: 
github_username: realkushagrakhare
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
