# Site settings
title: Kushagra Khare
description: Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kushagra Khare
user_description:
email: realkushagrakhare@outlook.com
twitter_username: 
github_username: realkushagrakhare
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
